### ISSUE TITLE
V12.122 and ImbrieKipp not on same scale

### ISSUE THREAD

**Issue by richardjtelford** [gavinsimpson/analogue#22]
Training set data ImbrieKipp seems to be percent; core data V12.122 seems to be proportion data. Makes analogue quality look very bad...
 
```
library(analogue)
data("ImbrieKipp")
rowSums(ImbrieKipp)# ~ 100
data(V12.122)
rowSums(V12.122) # ~1
```

**Comment by gavinsimpson** [comment]
Well that's just dumb. Thanks @richardjtelford; I'll fix this locally.

**Comment by gavinsimpson** [comment]
This is fixed; forgot to close
